import { writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import {
  sharedColors,
  gtk3OnlyColors,
  gtk4OnlyColors,
  gnomePalette,
} from './mapping'

const THEME_DIR = join(__dirname, '..', 'theme')
const GTK3_DIR = join(THEME_DIR, 'gtk-3.0')
const GTK4_DIR = join(THEME_DIR, 'gtk-4.0')

type Mode = 'light' | 'dark'
const IDX = { light: 1, dark: 2 } as const

function defineColor(name: string, value: string): string {
  return `@define-color ${name} ${value};`
}

function section(title: string, rows: [string, string][]): string {
  return `/* ${title} */\n` + rows.map(([n, v]) => defineColor(n, v)).join('\n')
}

// ── GTK3 gtk.css / gtk-dark.css ──────────────────────────────────────────────

function generateGtk3(mode: Mode): string {
  const i = IDX[mode]
  const shared  = sharedColors.map(r => [r[0], r[i]] as [string, string])
  const gtk3    = gtk3OnlyColors.map(r => [r[0], r[i]] as [string, string])
  const palette = gnomePalette as [string, string][]

  return [
    `/* Flexoki ${mode === 'light' ? 'Light' : 'Dark'} — GTK3 named colors */`,
    `/* Generated by gtk/src/generate.ts — do not edit by hand */`,
    '',
    section('Shared semantic colors', shared),
    '',
    section('GTK3-specific colors', gtk3),
    '',
    section('GNOME palette (Flexoki override)', palette),
    '',
    `@import 'widgets${mode === 'dark' ? '-dark' : ''}.css';`,
    '',
  ].join('\n')
}

// ── GTK4 gtk.css / gtk-dark.css ──────────────────────────────────────────────

function generateGtk4(mode: Mode): string {
  const i = IDX[mode]
  const shared = sharedColors.map(r => [r[0], r[i]] as [string, string])
  const gtk4   = gtk4OnlyColors.map(r => [r[0], r[i]] as [string, string])

  return [
    `/* Flexoki ${mode === 'light' ? 'Light' : 'Dark'} — GTK4 / libadwaita named colors */`,
    `/* Generated by gtk/src/generate.ts — do not edit by hand */`,
    '',
    section('Shared semantic colors', shared),
    '',
    section('GTK4-only colors (secondary sidebar)', gtk4),
    '',
    `/* libadwaita widget styles + GNOME palette overrides */`,
    `@import '../gtk-3.0/libadwaita.css';`,
    `@import '../gtk-3.0/libadwaita-tweaks.css';`,
    '',
  ].join('\n')
}

// ── libadwaita-tweaks.css (static fix + generated GNOME palette) ─────────────

function generateLibadwaitaTweaks(): string {
  const paletteBlock = (gnomePalette as [string, string][])
    .map(([n, v]) => defineColor(n, v))
    .join('\n')

  return [
    `/*`,
    ` * Fixes for legacy widget styles not covered by libadwaita.`,
    ` * Also overrides GNOME palette colors with Flexoki equivalents.`,
    ` * Generated by gtk/src/generate.ts — do not edit by hand`,
    ` */`,
    '',
    `/* Notebook header background */`,
    `notebook > header {`,
    `  background-color: @headerbar_bg_color;`,
    `  border-color: mix(currentColor, @window_bg_color, 0.85);`,
    `}`,
    '',
    `/* GNOME palette → Flexoki override */`,
    `/* Must come after libadwaita.css import so these definitions win */`,
    paletteBlock,
    '',
  ].join('\n')
}

// ── main ──────────────────────────────────────────────────────────────────────

function main() {
  mkdirSync(GTK3_DIR, { recursive: true })
  mkdirSync(GTK4_DIR, { recursive: true })

  const files: [string, string][] = [
    [join(GTK3_DIR, 'gtk.css'),              generateGtk3('light')],
    [join(GTK3_DIR, 'gtk-dark.css'),         generateGtk3('dark')],
    [join(GTK4_DIR, 'gtk.css'),              generateGtk4('light')],
    [join(GTK4_DIR, 'gtk-dark.css'),         generateGtk4('dark')],
    [join(GTK3_DIR, 'libadwaita-tweaks.css'), generateLibadwaitaTweaks()],
  ]

  for (const [path, content] of files) {
    writeFileSync(path, content, 'utf-8')
    console.log(`Generated: ${path.replace(join(__dirname, '../..'), '')}`)
  }
}

main()
