#!/usr/bin/env bash
set -euo pipefail

THEME_NAME="flexoki"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME_SRC="$SCRIPT_DIR/theme"
THEME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/themes/$THEME_NAME"
GTK4_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0"
GTK4_CSS="$GTK4_DIR/gtk.css"

GENERATED_HEADER="/* Flexoki GTK4 — generated by install.sh, do not edit by hand */"

if [[ ! -d "$THEME_SRC" ]]; then
    echo "Error: theme/ directory not found at $THEME_SRC" >&2
    exit 1
fi

echo "Installing $THEME_NAME GTK theme..."

# Install GTK3 theme files
mkdir -p "$THEME_DIR"
cp -r "$THEME_SRC"/. "$THEME_DIR/"
echo "  GTK3: $THEME_DIR"

# Install GTK4 user CSS.
#
# libadwaita ignores gtk-theme gsettings entirely. GTK4 only loads
# ~/.config/gtk-4.0/gtk.css — it does NOT load gtk-dark.css from user
# config when color-scheme changes. To support dark/light switching we
# generate a single combined file that uses @media (prefers-color-scheme: dark),
# which GTK4 4.x maps from the color-scheme gsettings value.
# Absolute @import paths avoid symlink relative-path resolution issues.
mkdir -p "$GTK4_DIR"

# Remove any old gtk-dark.css symlink left by a previous install
if [[ -L "$GTK4_DIR/gtk-dark.css" ]] && [[ "$(readlink "$GTK4_DIR/gtk-dark.css")" == "$THEME_DIR"* ]]; then
    rm "$GTK4_DIR/gtk-dark.css"
fi

light_colors=$(grep '^@define-color' "$THEME_DIR/gtk-4.0/gtk.css")
dark_colors=$(grep '^@define-color' "$THEME_DIR/gtk-4.0/gtk-dark.css" | sed 's/^/  /')

cat > "$GTK4_CSS" << CSSEOF
${GENERATED_HEADER}

/* Light mode colors */
${light_colors}

/* Dark mode overrides — responds to: gsettings set org.gnome.desktop.interface color-scheme prefer-dark */
@media (prefers-color-scheme: dark) {
${dark_colors}
}

/* Widget styles (absolute paths avoid symlink resolution issues) */
@import '${THEME_DIR}/gtk-3.0/libadwaita.css';
@import '${THEME_DIR}/gtk-3.0/libadwaita-tweaks.css';
CSSEOF

echo "  GTK4: $GTK4_CSS (generated)"

# Apply GTK3 theme via gsettings if available
if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.interface gtk-theme "$THEME_NAME"
    echo "  Applied via gsettings (GTK3)"
else
    echo "  gsettings not found — set the theme manually in your DE settings"
fi

echo "Done. GTK4 apps will pick up the theme on next launch."
echo "  Dark:  gsettings set org.gnome.desktop.interface color-scheme prefer-dark"
echo "  Light: gsettings set org.gnome.desktop.interface color-scheme prefer-light"
