#!/usr/bin/env bash
set -euo pipefail

THEME_NAME="flexoki"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME_SRC="$SCRIPT_DIR/theme"
THEME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/themes/$THEME_NAME"
GTK4_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0"
GTK4_CSS="$GTK4_DIR/gtk.css"

GENERATED_HEADER="/* Flexoki GTK4 — generated by install.sh, do not edit by hand */"

if [[ ! -d "$THEME_SRC" ]]; then
    echo "Error: theme/ directory not found at $THEME_SRC" >&2
    exit 1
fi

echo "Installing $THEME_NAME GTK theme..."

# ── GTK3 ─────────────────────────────────────────────────────────────────────
mkdir -p "$THEME_DIR"
cp -r "$THEME_SRC"/. "$THEME_DIR/"
echo "  GTK3: $THEME_DIR"

# ── GTK4 user CSS ─────────────────────────────────────────────────────────────
# libadwaita ignores the gtk-theme gsettings key entirely. GTK4 only loads
# ~/.config/gtk-4.0/gtk.css; it does NOT auto-load gtk-dark.css from user
# config when color-scheme changes (that variant mechanism only applies to
# files inside a theme directory). We generate a single self-contained file
# that uses @media (prefers-color-scheme: dark), which GTK4 4.x maps from
# the color-scheme gsettings value. Widget CSS is inlined so the generated
# file has no external dependencies and survives theme directory moves.
mkdir -p "$GTK4_DIR"

# Remove any old gtk-dark.css symlink left by a previous install
if [[ -L "$GTK4_DIR/gtk-dark.css" ]] && [[ "$(readlink "$GTK4_DIR/gtk-dark.css")" == "$THEME_DIR"* ]]; then
    rm "$GTK4_DIR/gtk-dark.css"
fi

light_colors=$(grep '^@define-color' "$THEME_DIR/gtk-4.0/gtk.css")
dark_colors=$(grep  '^@define-color' "$THEME_DIR/gtk-4.0/gtk-dark.css" | sed 's/^/  /')
widget_css=$(cat "$THEME_DIR/gtk-3.0/libadwaita.css")
tweaks_css=$(cat "$THEME_DIR/gtk-3.0/libadwaita-tweaks.css")

cat > "$GTK4_CSS" << CSSEOF
${GENERATED_HEADER}

/* ── Light mode colors ─────────────────────────────────────────────────── */
${light_colors}

/* ── Dark mode overrides ───────────────────────────────────────────────── */
/* Activated by: gsettings set org.gnome.desktop.interface color-scheme prefer-dark */
@media (prefers-color-scheme: dark) {
${dark_colors}
}

/* ── Widget styles (inlined — no external dependencies) ────────────────── */
${widget_css}

/* ── GNOME palette + libadwaita tweaks ─────────────────────────────────── */
${tweaks_css}
CSSEOF

echo "  GTK4: $GTK4_CSS (self-contained, $(wc -l < "$GTK4_CSS") lines)"

# ── Apply settings ────────────────────────────────────────────────────────────
if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.interface gtk-theme "$THEME_NAME"

    # Read the current color-scheme and keep it — don't override the user's
    # existing dark/light preference, just ensure the theme is applied.
    current_scheme=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null || echo "'default'")
    echo "  Applied via gsettings (GTK3, color-scheme: ${current_scheme})"

    # If still on default (no preference set), nudge the user.
    if [[ "$current_scheme" == "'default'" ]]; then
        echo ""
        echo "  Your color-scheme is currently 'default' (follows system)."
        echo "  To pin it:"
        echo "    Dark:  gsettings set org.gnome.desktop.interface color-scheme prefer-dark"
        echo "    Light: gsettings set org.gnome.desktop.interface color-scheme prefer-light"
    fi
else
    echo "  gsettings not found — set gtk-theme manually in your DE settings"
fi

echo ""
echo "Done. Restart running apps to pick up the new theme."
