#!/usr/bin/env bash
set -euo pipefail

THEME_NAME="flexoki"
THEME_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/themes/$THEME_NAME"
GTK4_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0"
GTK4_CSS="$GTK4_DIR/gtk.css"

GENERATED_HEADER="/* Flexoki GTK4 — generated by install.sh, do not edit by hand */"

echo "Uninstalling $THEME_NAME GTK theme..."

# Remove generated GTK4 CSS (only if it was written by our install.sh)
if [[ -f "$GTK4_CSS" ]] && ! [[ -L "$GTK4_CSS" ]] && head -1 "$GTK4_CSS" | grep -qF "$GENERATED_HEADER"; then
    rm "$GTK4_CSS"
    echo "  Removed: $GTK4_CSS"
fi

# Remove old-style symlinks left by earlier installs
for f in gtk.css gtk-dark.css; do
    target="$GTK4_DIR/$f"
    if [[ -L "$target" ]] && [[ "$(readlink "$target")" == "$THEME_DIR"* ]]; then
        rm "$target"
        echo "  Removed symlink: $target"
    fi
done

# Remove theme directory
if [[ -d "$THEME_DIR" ]]; then
    rm -rf "$THEME_DIR"
    echo "  Removed: $THEME_DIR"
fi

# Reset gsettings
if command -v gsettings &>/dev/null; then
    current=$(gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null || true)
    if [[ "$current" == "'$THEME_NAME'" ]]; then
        gsettings reset org.gnome.desktop.interface gtk-theme
        echo "  Reset gtk-theme via gsettings"
    fi
fi

echo "Done."
